#!/bin/sh
Rscript f_grid.R Al_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Bi_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Ca_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Cd_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Cr_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Cr_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Cs_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Cu_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Cu_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Fe_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R K_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Li_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Li_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Mg_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Mg_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Mn_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Mn_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Mo_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Mo_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Na_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Na_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Ni_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Pb_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Pb_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R PM10.rds $1 $2 $3 $4 & 
Rscript f_grid.R Rb_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Sb_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Sn_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Sn_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Sr_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Ti_i.rds $1 $2 $3 $4 & 
Rscript f_grid.R Tl_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R V_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R W_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Zn_s.rds $1 $2 $3 $4 & 
Rscript f_grid.R Zr_i.rds $1 $2 $3 $4 & 