#!/bin/sh

# traccianti ####
# 
# Rscript scelta_modello.R Al_i scelte &                                                                                      
# Rscript scelta_modello.R Al_s scelte &
# Rscript scelta_modello.R As_i scelte &
# Rscript scelta_modello.R As_s scelte &
# Rscript scelta_modello.R B_i scelte &
# Rscript scelta_modello.R B_s scelte &
# Rscript scelta_modello.R Ba_i scelte &
# Rscript scelta_modello.R Ba_s scelte &
# Rscript scelta_modello.R Bi_i scelte &
# Rscript scelta_modello.R Bi_s scelte &
# Rscript scelta_modello.R Ca_i scelte &
# Rscript scelta_modello.R Ca_s scelte &
# Rscript scelta_modello.R Cd_i scelte &
# Rscript scelta_modello.R Cd_s scelte &
# Rscript scelta_modello.R Ce_i scelte &
# Rscript scelta_modello.R Ce_s scelte &
# Rscript scelta_modello.R Co_i scelte &
# Rscript scelta_modello.R Co_s scelte &
# Rscript scelta_modello.R Cr_i scelte &
# Rscript scelta_modello.R Cr_s scelte &
# Rscript scelta_modello.R Cs_i scelte &
# Rscript scelta_modello.R Cs_s scelte &
# Rscript scelta_modello.R Cu_i scelte &
# Rscript scelta_modello.R Cu_s scelte &
# Rscript scelta_modello.R Fe_i scelte &
# Rscript scelta_modello.R Fe_s scelte &
# Rscript scelta_modello.R Ga_i scelte &
# Rscript scelta_modello.R Ga_s scelte &
# Rscript scelta_modello.R K_i scelte &
# Rscript scelta_modello.R K_s scelte &
# Rscript scelta_modello.R La_i scelte &
# Rscript scelta_modello.R La_s scelte &
# Rscript scelta_modello.R Li_i scelte &
# Rscript scelta_modello.R Li_s scelte &
# Rscript scelta_modello.R Mg_i scelte &
# Rscript scelta_modello.R Mg_s scelte &
# Rscript scelta_modello.R Mn_i scelte &
# Rscript scelta_modello.R Mn_s scelte &
# Rscript scelta_modello.R Mo_i scelte &
# Rscript scelta_modello.R Mo_s scelte &
# Rscript scelta_modello.R Na_i scelte &
# Rscript scelta_modello.R Na_s scelte &
# Rscript scelta_modello.R Nb_i scelte &
# Rscript scelta_modello.R Nb_s scelte &
# Rscript scelta_modello.R Ni_i scelte &
# Rscript scelta_modello.R Ni_s scelte &
# Rscript scelta_modello.R PM10 scelte &
# Rscript scelta_modello.R Pb_i scelte &
# Rscript scelta_modello.R Pb_s scelte &
# Rscript scelta_modello.R Rb_i scelte &
# Rscript scelta_modello.R Rb_s scelte &
# Rscript scelta_modello.R Sb_i scelte &
# Rscript scelta_modello.R Sb_s scelte &
# Rscript scelta_modello.R Sn_i scelte &
# Rscript scelta_modello.R Sn_s scelte &
# Rscript scelta_modello.R Sr_i scelte &
# Rscript scelta_modello.R Sr_s scelte &
# Rscript scelta_modello.R Ti_i scelte &
# Rscript scelta_modello.R Ti_s scelte &
# Rscript scelta_modello.R Tl_i scelte &
# Rscript scelta_modello.R Tl_s scelte &
# Rscript scelta_modello.R U_i scelte &
# Rscript scelta_modello.R U_s scelte &
# Rscript scelta_modello.R V_i scelte &
# Rscript scelta_modello.R V_s scelte &
# Rscript scelta_modello.R W_i scelte &
# Rscript scelta_modello.R W_s scelte &
# Rscript scelta_modello.R Zn_i scelte &
# Rscript scelta_modello.R Zn_s scelte &
# Rscript scelta_modello.R Zr_i scelte &
# Rscript scelta_modello.R Zr_s scelte &
