#!/bin/sh

Rscript scelta_modello.R PM10
Rscript scelta_modello.R As_s
Rscript scelta_modello.R Ba_s
Rscript scelta_modello.R Bi_i
Rscript scelta_modello.R Cd_s
Rscript scelta_modello.R Ce_i
Rscript scelta_modello.R Co_i
Rscript scelta_modello.R Cr_i
Rscript scelta_modello.R Cr_s
Rscript scelta_modello.R Cs_i
Rscript scelta_modello.R Cs_s
Rscript scelta_modello.R Cu_i
Rscript scelta_modello.R Fe_i
Rscript scelta_modello.R Ga_s
Rscript scelta_modello.R K_s
Rscript scelta_modello.R La_i
Rscript scelta_modello.R Li_i
Rscript scelta_modello.R Mn_i
Rscript scelta_modello.R Mn_s
Rscript scelta_modello.R Mo_s
Rscript scelta_modello.R Nb_i
Rscript scelta_modello.R Ni_i
Rscript scelta_modello.R Pb_i
Rscript scelta_modello.R Rb_i
Rscript scelta_modello.R Rb_s
Rscript scelta_modello.R Sb_i
Rscript scelta_modello.R Sn_i
Rscript scelta_modello.R Sr_i
Rscript scelta_modello.R Tl_s
Rscript scelta_modello.R U_i
Rscript scelta_modello.R W_i
Rscript scelta_modello.R W_s
Rscript scelta_modello.R Zn_s
Rscript scelta_modello.R Zr_i