---
title: "Terni"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

{
  # library(sf)
  library(dplyr)
  library(ggplot2)
  library(chron)
  library(readxl)
  library(glue)
  library(lubridate)
  library(readr)
  library(purrr)
  library(stringr)
  library(mgcv)
  library(gratia)
  library(itsadug) # Load jtools
  library(knitr)
} 

getModel <- function(vars, df) {
  ms <- 
    lapply(vars, function(x) {
      case_when(
        x == "tp_median" ~ paste0("s(", x, ", k=3)"),
        x == "u10m_min" ~ paste0("s(", x, ", k=5)"),
        x == "u10m_max" ~ paste0("s(", x, ", k=8)"),
        x == "v10m_median" ~ paste0("s(", x, ", k=9)"),
        x == "wspeed_min" ~ paste0("s(", x, ", k=8)"),
        x == "pblmin_median" ~ paste0("s(", x, ", k=3)"),
        x == "pbl00_median" ~ paste0("s(", x, ", k=6)"),
        x == "pblmin_IQR" ~ paste0("s(", x, ", k=9)"),
        x == "pbl00_min" ~ paste0("s(", x, ", k=1)"),
        x == "s7_sup_200" ~ paste0("s(", x, ", k=3)"),
        x == "s5_sup_200" ~ paste0("s(", x, ", k=9)"),
        x == "s1_sup_200" ~ paste0("s(", x, ", k=7)"),
        x == "u10m_median" ~ paste0("s(", x, ", k=9)"),
        x == "pwspeed_min" ~ paste0("s(", x, ", k=7)"),
        .default = paste0("s(", x, ")")
      )
    }) %>% paste(collapse = " + ") 
  
  ms <- paste("gam(value ~ ", ms, ", gamma=1.4, family=gaussian(link=log), data = df)")
  
  cat("stringa modello: ", ms)
  mod <- eval(parse(text = ms))
  return(mod)
}

getSign <- function(mod) {
  summary(mod)$s.table %>% 
    as.data.frame() %>% 
    filter(`p-value` < 0.05) %>% 
    rownames() -> v_sign
  return(v_sign)
}

df <- read_csv("~/R/terni/data/dataframes/df_finale_lod.csv", show_col_types = FALSE)
df %>% mutate(
  TOT_CR = Biomass_Burning_CR + Soil_Dust_CR + Steel_Plant_CR + Road_Dust_CR + Brake_Dust_CR,
  TOT_NCR = Biomass_Burning_NCR + Soil_Dust_NCR + Steel_Plant_NCR + Road_Dust_NCR + Brake_Dust_NCR
) -> df
```


# CR

```{r, results='asis', echo=FALSE}

modelli_cr <- readRDS("~/R/terni/rds_indici/TOT_CR.rds")

index <- grep("TOT_CR", names(df))
names(df)[index] <- "value"
mod_cr <- getModel(names(modelli_cr), df)

gamtabs(mod_cr, type = "HTML")

cat("\n\n R²:", summary(mod_cr)$r.sq %>% round(3), "\n\n")

appraise(mod_cr) %>% print()

draw(mod_cr)
```




# NON CR

```{r, results='asis', echo=FALSE}

modelli_ncr <- readRDS("~/R/terni/rds_indici/TOT_NCR.rds")

index <- grep("TOT_CR", names(df))
names(df)[index] <- "value"
mod_ncr <- getModel(names(modelli_ncr), df)

gamtabs(mod_ncr, type = "HTML")

cat("\n\n R²:", summary(mod_ncr)$r.sq %>% round(3), "\n\n")

appraise(mod_ncr) %>% print()
  
```

# NCR (clean)

```{r, results='asis', echo=FALSE}

v_sign <- getSign(mod_ncr)
lapply(v_sign, \(v) gsub("s\\(|\\)", '', v)) %>% unlist() -> v_sign

mod_ncr_clean <- getModel(v_sign, mod_ncr$model) 

gamtabs(mod_ncr_clean, type = "HTML")

cat("\n\n R²:", summary(mod_ncr_clean)$r.sq %>% round(3), "\n\n")

appraise(mod_ncr_clean) %>% print()

draw(mod_ncr_clean)
```
